spring:
  datasource:
    url: jdbc:h2:mem:spring-test;MODE=MariaDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: trace
        jpa: debug
